variables:
  
  TOOLKIT_NET_VERSION: '7.0.x'
  PathToMauiExtensionsCoreCsproj: 'src/zoft.MauiExtensions.Core/zoft.MauiExtensions.Core.csproj'

trigger:
- main

jobs:
  - job: build_library
    displayName: Build Library
    pool:
      vmImage: windows-latest
    steps:

      - task: UseDotNet@2
        displayName: Install .NET $(TOOLKIT_NET_VERSION)
        inputs:
          packageType: 'sdk'
          version: '$(TOOLKIT_NET_VERSION)'

      - task: CmdLine@2
        displayName: 'Install .NET MAUI Workload $(TOOLKIT_NET_VERSION)'
        inputs:
          script: dotnet workload restore $(PathToMauiExtensionsCoreCsproj)

      - task: NuGetToolInstaller@1
        displayName: 'Install Latest Nuget Package Manager'
        inputs:
          versionSpec: 
          checkLatest: true

      - task: CmdLine@2
        displayName: 'Build $(PathToMauiExtensionsCoreCsproj)'
        inputs:
          script: 'dotnet build -c Release $(PathToMauiExtensionsCoreCsproj)'

      - task: CopyFiles@2
        displayName: 'Copy nuget packages to staging directoy'
        inputs:
          Contents: 'src/zoft.MauiExtensions.Core/bin/Release/*.*nupkg'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish build output'
        inputs:
          PathtoPublish: $(Build.ArtifactStagingDirectory)
          ArtifactName: 'drop'
          publishLocation: 'Container'

  - job: 'publish_nuget_package'
    displayName: 'Publish NuGet Package'
    condition: ne(variables['Build.Reason'], 'PullRequest')
    dependsOn: build_library
    steps:

      - task: DownloadBuildArtifacts@0
        displayName: 'Download the published artifact'
        inputs:
          buildType: 'current'
          downloadType: 'specific'
          downloadPath: '$(Build.ArtifactsDirectory)'

      - task: NuGetCommand@2
        displayName: 'Push the artifact to NuGet feed'
        inputs:
          command: 'push'
          packagesToPush: '$(Build.ArtifactDirectory)/*.*nupkg'
          nuGetFeedType: 'external'
          publishFeedCredentials: 'NuGet'