trigger:
- main

variables:
  BuildConfiguration: Release
  DotNetVersion: 6.0.403
  VSVERSION: 17.4.0

pool:
  vmImage: 'windows-2022'
  demands:
  - MSBuild

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildMauiProject
        displayName: 'Build zoft.MauiExtensions.Core'
        steps:
          - task: UseDotNet@2
            displayName: .NET Version
            inputs:
              packageType: 'sdk'
              version: '$(DotNetVersion)'
          - task: CmdLine@2
            inputs:
              script: 'dotnet workload restore src\zoft.MauiExtensions.Core\zoft.MauiExtensions.Core.csproj'
          - task: NuGetToolInstaller@1
            inputs:
              versionSpec: 
              checkLatest: true
          - task: NuGetCommand@2
            inputs:
              command: 'restore'
              restoreSolution: 'src/zoft.MauiExtensions.sln'
              feedsToUse: 'select'
          - task: VSBuild@1
            inputs:
              solution: 'src\zoft.MauiExtensions.sln'
              configuration: 'release'
              clean: true