//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoft.MauiExtensions.Sample.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("zoft.MauiExtensions.Sample.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writting on the TriggerText entry, will trigger an update the TargetText and the TargeDate.
        /// </summary>
        internal static string DependsOnPage_MainLabel {
            get {
                return ResourceManager.GetString("DependsOnPage_MainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DependsOn.
        /// </summary>
        internal static string DependsOnPage_Title {
            get {
                return ResourceManager.GetString("DependsOnPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LocalizationPage_ChooseLanguageLabel {
            get {
                return ResourceManager.GetString("LocalizationPage_ChooseLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is Lorem Ipsum?.
        /// </summary>
        internal static string LocalizationPage_Label1 {
            get {
                return ResourceManager.GetString("LocalizationPage_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&apos;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing so [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LocalizationPage_Label2 {
            get {
                return ResourceManager.GetString("LocalizationPage_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eu odio feugiat, vehicula est sed, tincidunt ante. Nulla eu elementum nulla, sit amet molestie mauris. Vestibulum eu metus leo. Nam volutpat condimentum ipsum, in viverra nisl pulvinar eget. Nullam et feugiat elit. Sed id laoreet tortor. Sed viverra, felis et faucibus pharetra, enim magna bibendum libero, in fermentum arcu erat sed neque. Aenean hendrerit euismod augue vitae pretium. Aenean vulputate dolor eu magna tempor malesuada. Pellentesqu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LocalizationPage_Label3 {
            get {
                return ResourceManager.GetString("LocalizationPage_Label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization.
        /// </summary>
        internal static string LocalizationPage_Title {
            get {
                return ResourceManager.GetString("LocalizationPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doing work in background thread.
        /// </summary>
        internal static string MainThreadPage_BusyMessage {
            get {
                return ResourceManager.GetString("MainThreadPage_BusyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string MainThreadPage_ExecuteButtonLabel {
            get {
                return ResourceManager.GetString("MainThreadPage_ExecuteButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message coming from background thread and shown with MainThreadService.
        /// </summary>
        internal static string MainThreadPage_Message {
            get {
                return ResourceManager.GetString("MainThreadPage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Thread.
        /// </summary>
        internal static string MainThreadPage_Title {
            get {
                return ResourceManager.GetString("MainThreadPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DependsOn Sample.
        /// </summary>
        internal static string MenuItem_DependsOnLabel {
            get {
                return ResourceManager.GetString("MenuItem_DependsOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization Sample.
        /// </summary>
        internal static string MenuItem_LocalizationLabel {
            get {
                return ResourceManager.GetString("MenuItem_LocalizationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainThread Sample.
        /// </summary>
        internal static string MenuItem_MainThreadLabel {
            get {
                return ResourceManager.GetString("MenuItem_MainThreadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Sample.
        /// </summary>
        internal static string MenuItem_ValidationLabel {
            get {
                return ResourceManager.GetString("MenuItem_ValidationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon....
        /// </summary>
        internal static string ValidationPage_ComingSoon {
            get {
                return ResourceManager.GetString("ValidationPage_ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string ValidationPage_Tile {
            get {
                return ResourceManager.GetString("ValidationPage_Tile", resourceCulture);
            }
        }
    }
}
